domain_path: /home/master26/ems26/e.chinnaya/Documents/plane_sw_4/plane/export/plane/sw/standalone_ps7_cortexa9_0
app_src_dir: /usr/local/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
