set_property SRC_FILE_INFO {cfile:{/home/master26/ems26/e.chinnaya/Downloads/Plane Project-20251202/plane.xdc} rfile:{../../../../../Downloads/Plane Project-20251202/plane.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T14 [get_ports servo_0_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T15 [get_ports servo_1_0]
