domain_path: /home/master26/ems26/e.chinnaya/Documents/plane_sw/plane/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /usr/local/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
lang: c
